---
# 1. entrypoint is defined at commandline
# 2. traefik docker image does not have the directory /etc/traefik
# So we need to volume mount the config file traefik.yml at /etc/
services:
  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    hostname: "traefik"
    command:
      - "--api.insecure=true"
      - "--log.level=DEBUG"
      - "--entrypoints.gpt_ep.address=:8001"
      - "--entrypoints.grafana_ep.address=:3000"
      - "--entrypoints.ollama_ep.address=:11434"
      - "--providers.file.filename=/etc/traefik.yml"
    ports:
      - "11434:11434"
      - "3000:3000"
      - "8001:8001"
      - "8080:8080" # Traefik Dashboard
    volumes:
      - "./traefik/traefik.yml:/etc/traefik.yml:ro"
